# Site
name: "Vespa Blog"
title: "Vespa Blog"
description: "Blog for Vespa - The open big data serving engine"
logo: 'assets/images/Vespa_Logo_Black.png'
favicon: 'assets/icons/favicon-32x32.png'
baseurl:
mailchimp-list: 'https://vespa.ai/mailing-list.html'
include: ["_pages"]
permalink: /:title/
google_analytics: UA-107187180-2
enable_featured: false

# Authors
authors:
  bratseth:
    name: Jon Bratseth
    display_name: Jon Bratseth
    avatar: '/assets/avatars/bratseth.jpg'
    email: bratseth@verizonmedia.com
    twitter: https://twitter.com/jonbratseth
    description: "Vespa Chief Architect"
  geirst:
    name: Geir Storli
    display_name: Geir Storli
    avatar: '/assets/avatars/geirst.jpg'
    email: geirst@verizonmedia.com
    description: "Principle Vespa Engineer"
  kkraune:
    name: Kristian Aune
    display_name: Kristian Aune
    avatar: '/assets/avatars/kkraune.jpg'
    email: kraune@verizonmedia.com
    description: "Vespa Technical Product Manager"
  thigm85:
    name: Thiago Martins
    display_name: Thiago Martins
    avatar: '/assets/avatars/thigm85.jpg'
    email: tmartins@verizonmedia.com
    description: "Vespa Data Scientist"
  jobergum:
    name: Jo Kristian Bergum
    display_name: Jo Kristian Bergum
    avatar: '/assets/avatars/jobergum.jpg'
    email: bergum@verizonmedia.com
    description: "Vespa Solutions Architect"
  lesters:
    name: Lester Solbakken
    display_name: Lester Solbakken
    avatar: '/assets/avatars/lesters.jpg'
    email: lesters@verizonmedia.com
    description: "Principle Vespa Engineer"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 12
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, "*/README.md", Gemfile, Gemfile.lock, .idea, blog_index.json]

search:
  namespace: "blog"
  endpoint : "https://vespa-documentation-search.vespa.global.vespa.oath.cloud"
  do_feed  : true
  do_index_removal_before_feed: false
  feed_endpoints:
    - url: https://vespacloud-docsearch.vespa-team.aws-us-east-1c.public.vespa.oath.cloud/
      indexes:
        - blog_index.json
    - url: https://vespacloud-docsearch.vespa-team.aws-ap-northeast-1a.public.vespa.oath.cloud/
      indexes:
        - blog_index.json

defaults:
  -
    scope:
      path  : ""
    values:
      index : true
